using System.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Web.Resource;
using MyApp.Infrastructure;
using MyApp.Shared;

namespace MyApp.Server.Controllers;

[Authorize]
[ApiController] // Indicates that this is used to serve HTTP API responses.
[Route("api/[controller]")] // Convention which means the route (web url) will be whatever comes before Controller, in this case, Projects (ProjectsController)
[RequiredScope(RequiredScopesConfigurationKey = "AzureAd:Scopes")]
public class ProjectsController : ControllerBase // Inherits from ControllerBase. Controllerbase does not have view support (from MVC). If we want view support we can inherit from Controller. Controllerbase has http codes Ok = 200, etc.
{
    // Dependency injection
    private readonly ILogger<ProjectsController> _logger;
    private readonly IProjectRepository _repository;

    public ProjectsController(ILogger<ProjectsController> logger, IProjectRepository repository)
    {
        _logger = logger;
        _repository = repository;
    }

    // Get all projects from DB
    [AllowAnonymous]
    // This attribute below produces more descriptive response details for web API help pages generated by tools like Swagger.
    [ProducesResponseType(StatusCodes.Status200OK)] // Here the ActionResultType is inferred from the T in ActionResult<T>. This is an advantage over using IActionResult which is another option.
    [HttpGet] // Lets the web API know this is a get method. I.e we want to use the HTTP request method "get"
    // ActionResults represent various HTTP status codes. 
    // ControllerBase has "convenience methods" like Ok(), BadRequest(), etc. which is a shorthand for return new BadRequestResult();
    // C# doesn't support implicit cast operators on interfaces. Consequently, conversion of the interface to a concrete type is
    // necessary to use ActionResult<T>. 
    public async Task<ActionResult<IReadOnlyCollection<ProjectDTO>>> GetAll()
    {
        var projects = await _repository.GetAllProjects();
        return Ok(projects);
    }

    // Get project from projectID from DB
    [AllowAnonymous]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [HttpGet("id/{id}")]
    public async Task<ActionResult<ProjectDTO>> GetFromId(int id)
    {
        if (id < 0)
        {
            return BadRequest("ids can't be negative");
        }

        var project = await _repository.GetProjectFromID(id);

        if (project == null)
        {
            return NotFound("No Project with specified id");
        }

        return Ok(project);
    }

    // Get projects from Name from DB
    [AllowAnonymous]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [HttpGet("name/{name}")]
    public async Task<ActionResult<IReadOnlyCollection<ProjectDTO>>> GetFromName(string name)
    {
        if (name.Length == 0 || name == null)
        {
            return BadRequest("No name provided");
        }

        var projects = await _repository.GetProjectsFromName(name);

        if (projects.Count == 0)
        {
            return NotFound("No Project with specified name");
        }
        return Ok(projects);
    }

    [AllowAnonymous]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ProjectDTO), StatusCodes.Status200OK)]
    [HttpGet("tags/{tags}")]
    public async Task<ActionResult<IReadOnlyCollection<ProjectDTO>>> GetFromTags(string tags)
    {
        string[] tagList = tags.Split("_");
        if (tagList.Length == 0 || (tagList.Length == 1 && tagList.ElementAt(0) == ""))
        {
            return BadRequest("No tags provided");
        }

        var projects = await _repository.GetProjectsFromTags(tagList.ToList());

        if (projects.Count == 0)
        {
            return NotFound("No Project with specified tags");
        }

        return Ok(projects);
    }

    [AllowAnonymous]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ProjectDTO), StatusCodes.Status200OK)]
    [HttpGet("tags/{tags}/{name}")]
    public async Task<ActionResult<IReadOnlyCollection<ProjectDTO>>> GetFromTagsAndTitle(string tags, string name)
    {
        string[] tagList = tags.Split("_");
        if (tagList.Length == 0 || (tagList.Length == 1 && tagList.ElementAt(0) == "")
            || name.Length == 0 || name == null)
        {
            return BadRequest("No tags / title provided");
        }

        var projects = await _repository.GetProjectsFromTagsAndName(tagList.ToList(), name);

        if (projects.Count == 0)
        {
            return NotFound("No Project with specified tags");
        }
        return Ok(projects);
    }

    [Authorize]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(409)]
    [ProducesResponseType(typeof(ProjectDTO), StatusCodes.Status201Created)]
    [HttpPost]
    public async Task<ActionResult<ProjectDTO>> CreateProject(ProjectCreateDTO inputProject)
    {
        if (inputProject.Name.Length == 0
        || inputProject.StartDate == null
        || inputProject.EndDate == null
        || inputProject.Description.Length == 0)
        {
            return BadRequest("Not correct input");
        }

        var (statuscode, created) = await _repository.CreateProject(inputProject);

        switch (statuscode)
        {
            case Status.Conflict:
                return Conflict(created);
            case Status.Created:
                return Created(new Uri("/api/Projects", UriKind.Relative), created); //CreatedAtAction(nameof(GetFromId), new {created.Id}, created);
            default:
                return BadRequest();
        }
    }

    [Authorize]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [HttpPut("id/{id}")]
    public async Task<ActionResult<ProjectDTO>> UpdateProject(int id, [FromBody] ProjectUpdateDTO inputProject)
    {
        if (inputProject.Name.Length == 0
        || inputProject.StartDate == null
        || inputProject.EndDate == null
        || inputProject.Description.Length == 0)
        {
            return BadRequest("Not correct input");
        }

        var status = await _repository.UpdateProject(inputProject.Id, inputProject);

        switch (status)
        {
            case Status.NotFound:
                return NotFound("Project not found");
            case Status.Updated:
                return Ok();
            default:
                return BadRequest();
        }
    }

    [Authorize]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [HttpDelete("id/{id}")]
    public async Task<ActionResult<ProjectDTO>> Delete(int id)
    {
        var status = await _repository.DeleteProject(id);

        if (status == Status.NotFound)
        {
            return NotFound("The project wasnt found");
        }
        else
        {
            return Ok();
        }
    }
}